---
title: "Wrangling"
author: "Carter Martindale"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
library(lubridate)
library(janitor)
library(rstanarm)
library(readxl)
library(tidymodels)
library(gtsummary)
library(broom.mixed)
```

This is where I did the majority of my actual coding until 
I moved it into separate R files that I could then source 
into my shinyapp. For more commented out/explained lines of code see the .R documents inside of the SCOTUS_APP file.

## SC case centered

```{r case}

# Basic reading in of my first dataset that I wanted to
# start messing with. 

d<- read_csv("raw_data/SCDB_2020_01_caseCentered_LegalProvision.csv", col_names = TRUE, cols(
  caseId = col_character(),
  docketId = col_character(),
  caseIssuesId = col_character(),
  voteId = col_character(),
  dateDecision = col_character(),
  decisionType = col_double(),
  usCite = col_character(),
  sctCite = col_character(),
  ledCite = col_character(),
  lexisCite = col_character(),
  term = col_double(),
  naturalCourt = col_double(),
  chief = col_character(),
  docket = col_character(),
  caseName = col_character(),
  dateArgument = col_character(),
  dateRearg = col_character(),
  petitioner = col_double(),
  petitionerState = col_double(),
  respondent = col_double(),
  respondentState = col_double(),
  jurisdiction = col_double(),
  adminAction = col_double(),
  adminActionState = col_double(),
  threeJudgeFdc = col_double(),
  caseOrigin = col_double(),
  caseOriginState = col_double(),
  caseSource = col_double(),
  caseSourceState = col_double(),
  lcDisagreement = col_double(),
  certReason = col_double(),
  lcDisposition = col_double(),
  lcDispositionDirection = col_double(),
  declarationUncon = col_double(),
  caseDisposition = col_double(),
  caseDispositionUnusual = col_double(),
  partyWinning = col_double(),
  precedentAlteration = col_double(),
  voteUnclear = col_double(),
  issue = col_double(),
  issueArea = col_double(),
  decisionDirection = col_double(),
  decisionDirectionDissent = col_double(),
  authorityDecision1 = col_double(),
  authorityDecision2 = col_double(),
  lawType = col_double(),
  lawSupp = col_double(),
  lawMinor = col_character(),
  majOpinWriter = col_double(),
  majOpinAssigner = col_double(),
  splitVote = col_double(),
  majVotes = col_double(),
  minVotes = col_double()
)) %>% 
  clean_names()

d_reformat <- d %>% 
  mutate(date_decision_new = mdy(date_decision),
         date_argument_new = mdy(date_argument),
         date_rearg_new = mdy(date_rearg))

# Here I created a new date column that would be workable as
# a date rather than simply a character, and I cleaned up
# the names. 

```

```{r plot}

# My first plot that is currently on the "interesting findings"
# page which shows all of the decisions by the courts
# under each Chief Justice. This is a sort of top level
# picture of my main question for this app- can we predict
# the way a court is going to vote (since there are "liberal"
# and "conservative" courts), or can we predict which cases
# a court is going to choose?

d_reformat %>% 
  group_by(issue_area) %>% 
  filter(issue_area %in% c(2, 3, 5)) %>% 
  ggplot(aes(x = issue_area, fill = chief)) +
  geom_bar(position = "dodge") +
  facet_wrap(~decision_direction)

# All of the following plots were simply methods of data 
# exploration- I wanted to see how different groups of the
# data looked when displayed in different ways. 

d_reformat %>% 
  ggplot(aes(x = issue_area, fill = chief)) +
  geom_bar(position = "dodge")

 d_reformat %>% 
  filter(decision_direction %in% c(1, 2)) %>% 
  ggplot(aes(x = term, fill = chief)) +
  geom_bar(position = "dodge") +
  facet_wrap(~decision_direction,
             labeller = labeller(decision_direction = c(
               "1" = "Conservative", "2" = "Liberal"))) +
  scale_fill_discrete(name = "Chief",
                      breaks = c("Vinson", "Warren",
                                 "Burger", "Rehnquist",
                                 "Roberts")) +
  labs(title = "Direction of SCOTUS Rulings",
       x = "Term",
       y = "Number of Rulings")
 
 # This was a sort of final draft for a plot that I would
 # eventually include in my shiny app. It displays the 
 # direction of each vote from each Court broken down by 
 # chief and then faceted by decision direction, so liberal
 # will be in one pane and Conservative in another pane. 

```

```{r justice}

justice <- read_csv("raw_data/SCDB_2020_01_justiceCentered_Citation.csv", col_names = TRUE, cols(
  caseId = col_character(),
  docketId = col_character(),
  caseIssuesId = col_character(),
  voteId = col_character(),
  dateDecision = col_character(),
  decisionType = col_double(),
  usCite = col_character(),
  sctCite = col_character(),
  ledCite = col_character(),
  lexisCite = col_character(),
  term = col_double(),
  naturalCourt = col_double(),
  chief = col_character(),
  docket = col_character(),
  caseName = col_character(),
  dateArgument = col_character(),
  dateRearg = col_character(),
  petitioner = col_double(),
  petitionerState = col_double(),
  respondent = col_double(),
  respondentState = col_double(),
  jurisdiction = col_double(),
  adminAction = col_double(),
  adminActionState = col_double(),
  threeJudgeFdc = col_double(),
  caseOrigin = col_double(),
  caseOriginState = col_double(),
  caseSource = col_double(),
  caseSourceState = col_double(),
  lcDisagreement = col_double(),
  certReason = col_double(),
  lcDisposition = col_double(),
  lcDispositionDirection = col_double(),
  declarationUncon = col_double(),
  caseDisposition = col_double(),
  caseDispositionUnusual = col_double(),
  partyWinning = col_double(),
  precedentAlteration = col_double(),
  voteUnclear = col_double(),
  issue = col_double(),
  issueArea = col_double(),
  decisionDirection = col_double(),
  decisionDirectionDissent = col_double(),
  authorityDecision1 = col_double(),
  authorityDecision2 = col_double(),
  lawType = col_double(),
  lawSupp = col_double(),
  lawMinor = col_character(),
  majOpinWriter = col_double(),
  majOpinAssigner = col_double(),
  splitVote = col_double(),
  majVotes = col_double(),
  minVotes = col_double(),
  justice = col_double(),
  justiceName = col_character(),
  vote = col_double(),
  opinion = col_double(),
  direction = col_double(),
  majority = col_double(),
  firstAgreement = col_double(),
  secondAgreement = col_double())) %>% 
  select(voteId, dateDecision, term, chief,
         caseOriginState, issue, issueArea,
         decisionDirection, justice, justiceName, vote,
         decisionDirectionDissent, majOpinWriter,
         direction) %>% 
  clean_names() %>% 
  drop_na(direction)

justice$direction[which(justice$direction == 2)] <- 0

# This was my first big initial read in of my second dataset,
# one that focused more on the individual decisions of the
# justices rather than the overall court decisions. 

justice_2 <- justice %>%
  select(term, chief,
         issue_area,
         decision_direction, justice, justice_name, vote,
         decision_direction_dissent, maj_opin_writer,
         direction) %>% 
  drop_na(direction)

# I cut down the set to include only those variables that
# I thought relevant/that I wanted to take a closer look
# at. 

justice_2$issue_area[which(justice_2$issue_area == 1)] <- "Criminal Procedure"
justice_2$issue_area[which(justice_2$issue_area == 2)] <- "Civil Rights"
justice_2$issue_area[which(justice_2$issue_area == 3)] <- "1st Amendment"
justice_2$issue_area[which(justice_2$issue_area == 4)] <- "Due Process"
justice_2$issue_area[which(justice_2$issue_area == 5)] <- "Privacy"
justice_2$issue_area[which(justice_2$issue_area == 6)] <- "Attorney/Government Fees and Compensation"
justice_2$issue_area[which(justice_2$issue_area == 7)] <- "Unions"
justice_2$issue_area[which(justice_2$issue_area == 8)] <- "Economic Activity"
justice_2$issue_area[which(justice_2$issue_area == 9)] <- "Judicial Power"
justice_2$issue_area[which(justice_2$issue_area == 10)] <- "Federalism"
justice_2$issue_area[which(justice_2$issue_area == 11)] <- "Interstate Relations"
justice_2$issue_area[which(justice_2$issue_area == 12)] <- "Federal Taxation"
justice_2$issue_area[which(justice_2$issue_area == 13)] <- "Misc"
justice_2$issue_area[which(justice_2$issue_area == 14)] <- "Private Laws"

# The Issue Areas were originally classified by numbers, but for the sake of convenience on my shinyapp this is where
# I learned to change up those numbers to names that
# would make sense to a user. 

```

```{r more analysis}

summary(justice)

case_reformat %>% 
        filter(issue_area == 3) %>% 
        ggplot(aes(x = issue_area, fill = chief)) +
            geom_bar(position = "dodge")

# More exploratory analysis to see how the data that falls 
# under issue area 3 looks like. After looking at it I felt
# comfortable continuing with making a stan_glm. 

fit <- justice %>% 
            filter(justice_name %in% c("JGRoberts", "CThomas",
                                       "SGBreyer", "SAAlito",
                                       "SSotomayor"),
                   issue_area == 3)

stan_glm(direction ~ justice_name - 1,
         data = fit,
         refresh = 0)

# I Had the idea of maybe looking for a cool distribution
# based on jurisdiction, but nothing really came of it
# so it didn't end up in my final project. 

d$jurisdiction[which(d$jurisdiction == 1)] <- "cert"
d$jurisdiction[which(d$jurisdiction == 2)] <- "appeal"
d$jurisdiction[which(d$jurisdiction == 3)] <- "bail"
d$jurisdiction[which(d$jurisdiction == 4)] <- "certification"
d$jurisdiction[which(d$jurisdiction == 5)] <- "docketing fee"
d$jurisdiction[which(d$jurisdiction == 6)] <- "rehearsing or restored to calendar for reargument"
d$jurisdiction[which(d$jurisdiction == 7)] <- "injunction"
d$jurisdiction[which(d$jurisdiction == 8)] <- "mandamus"
d$jurisdiction[which(d$jurisdiction == 9)] <- "original"
d$jurisdiction[which(d$jurisdiction == 10)] <- "prohibition"
d$jurisdiction[which(d$jurisdiction == 12)] <- "stay"
d$jurisdiction[which(d$jurisdiction == 13)] <- "writ of error"
d$jurisdiction[which(d$jurisdiction == 14)] <- "writ of habeus corpus"
d$jurisdiction[which(d$jurisdiction == 15)] <- "unspecified"

# Changed the variable name to something meaningful rather 
# than just a number that users/I would have to look up to 
# ascertain what exact jurisdiction the number meant. 


```
## Reading in petition data
```{r circuit court data}

# I needed to get data from the circuit courts regarding all 
# of the petitions for a writ of certiori, and lots of the
# data came in differently formatted spreadsheets (or even
# pdfs). So the following functions read in and clean the data
# into a form that I can then draw some meaningful analysis
# from.

read_petition_total <- function(x, y) {
  z <- read_excel(x, skip = 1) %>% 
    drop_na() %>% 
    clean_names() %>% 
    rename("granted" = "terminated",
           "denied" = "x5",
           "dismissed" = "x6",
           "nature_of_proceeding" = "circuit_and_nature_of_proceeding") %>% 
    mutate(year = y)
  # z[2:5, c(1, 3:6, 8)]
  w <- z[c(7:10, 12:15, 17:20, 22:25, 27:30, 32:35, 37:40,
           42:45, 47:50, 52:55, 57:60, 62:65), c(1, 3:6, 8)]
  w %>%
    mutate(district = c(rep("DC", 4), rep("1st", 4),
                        rep("2nd", 4), rep("3rd", 4),
                        rep("4th", 4), rep("5th", 4),
                        rep("6th", 4),
                        rep("7th", 4), rep("8th", 4),
                        rep("9th", 4), rep("10th", 4),
                        rep("11th", 4)))
}

# 2016 - 2019 can be read in using this formula

read_p <- function(x, y) {
  z <- read_excel(x, skip = 9
                  ) %>%
    drop_na() %>% 
    clean_names() %>% 
    rename("nature_of_proceeding" = "of_proceeding") %>% 
    mutate(year = y)
  w <- z[c(7:10, 12:15, 17:20, 22:25, 28:31, 33:36, 38:41,
           43:46, 48:51, 54:57, 59:62, 64:67), c(1, 3:6, 8)]
  
  w %>%
    mutate(district = c(rep("DC", 4), rep("1st", 4),
                        rep("2nd", 4), rep("3rd", 4),
                        rep("4th", 4), rep("5th", 4),
                        rep("6th", 4),
                        rep("7th", 4), rep("8th", 4),
                        rep("9th", 4), rep("10th", 4),
                        rep("11th", 4)))
}

# 2005 - 2015 can be read in this way, with three exceptions
# addressed below

read_annoyed <- function(x, y) {
  z <- read_excel(x, skip = 11) %>% 
    drop_na() %>% 
    clean_names() %>% 
    rename("nature_of_proceeding" = "of_proceeding") %>% 
    mutate(year = y)
  # z[2:5, c(1, 3:6, 8)]
  w <- z[c(7:10, 12:15, 17:20, 22:25, 28:31, 33:36, 38:41,
           43:46, 48:51, 54:57, 59:62, 64:67), c(1, 3:6, 8)]
  w %>%
    mutate(district = c(rep("DC", 4), rep("1st", 4),
                        rep("2nd", 4), rep("3rd", 4),
                        rep("4th", 4), rep("5th", 4),
                        rep("6th", 4),
                        rep("7th", 4), rep("8th", 4),
                        rep("9th", 4), rep("10th", 4),
                        rep("11th", 4)))
}

# Basically the same formula as above, just needed to skip
# a few more rows of data for these two years for some reason.

read_2008 <- function(x, y) {
  z <- read_excel(x, skip = 9,
                  #   col_types = c("text", "numeric",
                  #                 "numeric", "numeric",
                  #                 "numeric", "numeric",
                  #                 "text")
                  ) %>%
    drop_na() %>% 
    clean_names() %>% 
    rename("nature_of_proceeding" = "of_proceeding") %>% 
    mutate(year = y)
  w <- z[c(7:10, 12:15, 17:20, 22:25, 28:31, 33:36, 38:41,
           43:46, 48:51, 53:56, 58:61, 63:66), c(1, 3:6, 8)]
  w %>%
    mutate(district = c(rep("DC", 4), rep("1st", 4),
                        rep("2nd", 4), rep("3rd", 4),
                        rep("4th", 4), rep("5th", 4),
                        rep("6th", 4),
                        rep("7th", 4), rep("8th", 4),
                        rep("9th", 4), rep("10th", 4),
                        rep("11th", 4)))
}

# 2008 was also a different year. I honestly probably spent
# just as much time figuring out the bugs in my formula
# as if I had just manually read in all of the data
# differently, but this was a nice way to check my progress
# and it was fun putting together a function.

p_2019 <- read_petition_total("raw_data/jb_b2_0930.2019.xlsx", 2019)
head(p_2019)
p_2018 <- read_petition_total("raw_data/jb_b2_0930.2018.xlsx", 2018)
p_2017 <- read_petition_total("raw_data/jb_b2_0930.2017.xlsx", 2017)
p_2016 <- read_petition_total("raw_data/jb_b2_0930.2016.xlsx", 2016)
p_2015 <- read_p("raw_data/B02Sep15.xlsx", 2015)
p_2014 <- read_p("raw_data/B02Sep14.xlsx", 2014)
p_2013 <- read_p("raw_data/B02Sep13.xlsx", 2013)
p_2012 <- read_p("raw_data/B02Sep12.xlsx", 2012)
p_2011 <- read_p("raw_data/B02Sep11.xlsx", 2011)
p_2010 <- read_annoyed("raw_data/B02Sep10.xlsx", 2010)
p_2009 <- read_p("raw_data/B02Sep09.xlsx", 2009)
p_2008 <- read_2008("raw_data/B02Sep08.xlsx", 2008)
p_2007 <- read_p("raw_data/B02Sep07.xlsx", 2007)
p_2006 <- read_annoyed("raw_data/b2_2.xlsx", 2006)
p_2005 <- read_p("raw_data/b2_1.xlsx", 2005)

p_2016$nature_of_proceeding[which(p_2016$nature_of_proceeding == "U.S. Private")] <- 
  "Private Civil"

# For some reason 2016 is the only year they called Private
# Civil U.S. Private, so we had to change that. 
  
roberts_circuit <- rbind(p_2019, p_2018, p_2017, p_2016, p_2015, p_2014, p_2013, p_2012, p_2011, p_2010, p_2009, p_2008, p_2007, p_2006, p_2005)

# I combined all of the petition data from the Roberts court
# into one dataset that I will be using to make a model later.

roberts_circuit$granted[which(roberts_circuit$granted ==
                                "-")] <- 0
roberts_circuit$denied[which(roberts_circuit$denied ==
                                "-")] <- 0
roberts_circuit$dismissed[which(roberts_circuit$dismissed ==
                                "-")] <- 0
roberts_circuit$filed[which(roberts_circuit$filed ==
                                "-")] <- 0

# To play around with the variables I needed to replace all
# of the hyphens (essentially NA's) with a numerical value.

roberts_circuit <- roberts_circuit %>%   
  mutate(percent_granted =
           (as.numeric(granted)/as.numeric(filed)) *100,
         percent_denied =
           (as.numeric(denied)/as.numeric(filed)) *100)

# I added these variables to use later on in my logit function

roberts_circuit$percent_granted[which(roberts_circuit$percent_granted == "NaN")] <- 0
roberts_circuit$percent_denied[which(roberts_circuit$percent_denied == "Inf")] <- 0

# Since there were a few rows that ended up with 0 divided by
# 0 I just manually changed those to be zero

```

```{r circuit court model}

roberts_model <- stan_glm(percent_granted ~
                            nature_of_proceeding + year
                          + district - 1,
         data = roberts_circuit,
         refresh = 0)
print(roberts_model, digits = 4)

# My first model- very simple, just regressing the percent of
# granted cases onto the nature of the case, the year
# it was petitioned, and the district it came from. 

roberts_intercept <- stan_glm(percent_granted ~
                            nature_of_proceeding + year
                          + district,
         data = roberts_circuit,
         refresh = 0)
print(roberts_intercept, digits = 4)

roberts_model_2 <- stan_glm(percent_granted ~
                            nature_of_proceeding*district,
         data = roberts_circuit,
         refresh = 0)
print(roberts_model_2, digits = 4)

# My second model- this one looked to see if there was any 
# significant interaction between the district a case came
# from and the nature of that case (IE is a criminal case more
# likely to be heard if it is from a certain district?).
# Using the MAD_SD, proceedings from the 11th Circuit,
# U.S. Civil cases from the 2nd Circuit, Criminal and U.S. Civil
# from the 3rd, Criminal from Circuit 4, Private Civil from
# Circuit 5, Criminal and U.S. Civil from Circuit 8,
# U.S. Civil from Circuit 9, and all proceedings from the
# DC Circuit disprove the null hypothesis. 

tbl_regression(roberts_intercept, intercept = TRUE) %>%
  as_gt() %>% 
  tab_header(title = "Regression of Granted Petitions for Writ of Certiori", 
               subtitle = "The Effect of case type, origin, and year on petition success") %>%
    tab_source_note(md("Source: Circuit Court Data"))

# w/ the intercept. Based on the MAD_SD, all of the nature
# predictions can be regarded as significant, in addition to 
# the value for year. Regarding individual districts,
# only Districts 3, 7, 9, 11, and DC disprove the null 
# hypothesis. 

tbl_regression(roberts_model_2, intercept = TRUE, 
               include = c("(Intercept)",
               "nature_of_proceeding:district")) %>% 
  as_gt() %>% 
  tab_header(title = "Regression of Granted Petitions for Writ of Certiori", 
               subtitle = "The Effect of case type and origin interaction on petition success") %>%
    tab_source_note(md("Source: Circuit Court Data"))

# This is the table output that I wanted to display, and so
# I used the include argument to only take a portion of the
# overall table/results of my regression. 

```

```{r justice model plots}

# This is where I did the heavy lifting for my 2nd model,
# one predicting how a certain Justice will vote on a given
# issue area. It was then a simple matter to change this code
# in my app.r file to be interactive.

fit <- justice_2 %>% 
  filter(justice_name %in% c("JGRoberts", "CThomas",
                                       "SGBreyer", "SAAlito",
                                       "SSotomayor"),
                   issue_area == "Economic Activity")

# what issue_area is filtered will ultimately be interactive.

fit_obj <- stan_glm(data = fit,
                    direction ~ justice_name - 1,
                    refresh = 0)
new_obj <- tibble(justice_name = c("JGRoberts", "CThomas",
                                       "SGBreyer", "SAAlito",
                                       "SSotomayor"))

# I decided to use posterior_epred since we aren't going to have
# values less than one. 

ep <- posterior_epred(fit_obj, newdata = new_obj) %>% 
  as_tibble() %>% 
  mutate_all(as.numeric) %>% 
  rename(Roberts = `1`,
         Thomas = `2`,
         Breyer = `3`,
         Alito = `4`,
         Sotomayor = `5`) %>% 
  pivot_longer(cols = Roberts:Sotomayor,
               names_to = "Justice",
               values_to = "Vote")

ep %>% 
ggplot(aes(x = Vote)) +
            geom_histogram(aes(y = after_stat(count/sum(count)),
                               fill = Justice),
                           alpha = 0.5, 
                           bins = 100, 
                           position = "identity",
                           color = "white") +
            geom_vline(xintercept = 0.5, lty = 2,
                       color = "red")

```


